build:
	g++ -Wall dinamica.cpp -o dinamica
	g++ -Wall greedy2.cpp -o greedy
	g++ -Wall bonus.cpp -o bonus

run-p1:
	./greedy

run-p2:
	./dinamica

run-p3:
	./bonus

clean:
	rm -f dinamica greedy bonus
